export const PROCESSING_START_REQUEST = 'PROCESSING_START_REQUEST';
export const PROCESSING_START = 'PROCESSING_START';
export const PROCESSING_STARTED = 'PROCESSING_STARTED';
export const PROCESSING_FINISHED = 'PROCESSING_FINISHED';
export const PROCESSING_ERROR = 'PROCESSING_ERROR';
export const PROCESSING_RECEIVE_STATUS = 'PROCESSING_RECEIVE_STATUS';
export const PROCESSING_COMPLETED = 'PROCESSING_COMPLETED';
export const PROCESSING_FAILED = 'PROCESSING_FAILED';
