export const VIDEO_LOADED_METADATA = 'VIDEO_LOADED_METADATA';
export const VIDEO_TIME_UPDATE = 'VIDEO_TIME_UPDATE';
export const VIDEO_PLAY = 'VIDEO_PLAY';
export const VIDEO_PAUSE = 'VIDEO_PAUSE';
export const VIDEO_SEEK = 'VIDEO_SEEK';
export const VIDEO_SEEKED = 'VIDEO_SEEKED';
